<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WinAirPlay.Core</RootNamespace>
    <AssemblyName>WinAirPlay.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WinAirPlay.Core.Tests" />
  </ItemGroup>

</Project>
