/** Clipboard body with isendai attribution for platforms without prefilled compose URLs. */
export function buildSocialShareClipboardBody(body: string, siteUrl: string): string {
  const site = siteUrl.replace(/\/$/, "");
  const trimmed = body.trim();
  const attribution = `— Generated by isendai.com ${site}`;
  return trimmed.length > 0 ? `${trimmed}\n\n${attribution}` : attribution;
}

export function publicSiteUrl(): string {
  const raw =
    typeof process !== "undefined" && process.env.NEXT_PUBLIC_SITE_URL
      ? process.env.NEXT_PUBLIC_SITE_URL.trim()
      : "";
  if (raw.length > 0) return raw.replace(/\/$/, "");
  return "https://isendai.com";
}

export function buildTweetIntentUrl(body: string, siteUrl: string): string {
  const site = siteUrl.replace(/\/$/, "");
  const suffix = ` — Generated by isendai.com ${site}`;
  const max = 280;
  const budget = Math.max(0, max - suffix.length);
  const trimmed = body.trim();
  const head =
    trimmed.length <= budget ? trimmed : `${trimmed.slice(0, Math.max(0, budget - 1))}…`;
  const full = `${head}${suffix}`;
  return `https://twitter.com/intent/tweet?text=${encodeURIComponent(full)}`;
}

export async function copyTextForSocialShare(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}
